"""next_send_time_to_varchar

Revision ID: 1577dcfbcb07
Revises: 9c6a51a8364a
Create Date: 2023-02-24 04:21:31.548534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1577dcfbcb07'
down_revision = '9c6a51a8364a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'scheduled_messages',
        'next_send_time',
        existing_type=sa.TIMESTAMP(),
        type_=sa.VARCHAR(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'scheduled_messages',
        'next_send_time',
        existing_type=sa.VARCHAR(),
        type_=sa.TIMESTAMP(),
    )
    # ### end Alembic commands ###
