"""гdelete message_id

Revision ID: 216179206ff0
Revises: 1ee299f599de
Create Date: 2023-02-25 16:34:49.012930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216179206ff0'
down_revision = '1ee299f599de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scheduled_messages_message_id_fkey', 'scheduled_messages', type_='foreignkey')
    op.drop_column('scheduled_messages', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_messages', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('scheduled_messages_message_id_fkey', 'scheduled_messages', 'messages', ['message_id'], ['message_id'])
    # ### end Alembic commands ###
