"""срchange foreign key rule

Revision ID: 30429ea12e82
Revises: 772ff6f1f180
Create Date: 2023-02-26 14:42:08.011029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30429ea12e82'
down_revision = '772ff6f1f180'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scheduled_messages_template_id_fkey', 'scheduled_messages', type_='foreignkey')
    op.drop_constraint('scheduled_messages_group_id_fkey', 'scheduled_messages', type_='foreignkey')
    op.create_foreign_key(None, 'scheduled_messages', 'templates', ['template_id'], ['template_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'scheduled_messages', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_messages', type_='foreignkey')
    op.drop_constraint(None, 'scheduled_messages', type_='foreignkey')
    op.create_foreign_key('scheduled_messages_group_id_fkey', 'scheduled_messages', 'groups', ['group_id'], ['group_id'])
    op.create_foreign_key('scheduled_messages_template_id_fkey', 'scheduled_messages', 'templates', ['template_id'], ['template_id'])
    # ### end Alembic commands ###
