"""deeltelete messages table

Revision ID: 34ffaf995872
Revises: 216179206ff0
Create Date: 2023-02-25 16:40:53.337456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34ffaf995872'
down_revision = '216179206ff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.add_column('templates', sa.Column('caption', sa.String(), nullable=True))
    op.add_column('templates', sa.Column('document', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'document')
    op.drop_column('templates', 'caption')
    op.create_table('messages',
    sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.template_id'], name='messages_template_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('message_id', name='messages_pkey')
    )
    # ### end Alembic commands ###
