"""fix next send time

Revision ID: 3a20365192c1
Revises: bf62e1c62b8b
Create Date: 2023-02-25 17:57:45.209504

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3a20365192c1'
down_revision = 'bf62e1c62b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column(
        'scheduled_messages',
        'next_send_time',
    )
    op.add_column(
        'scheduled_messages',
        sa.Column(
            'next_send_time',
            sa.TIMESTAMP(),
            nullable=True,
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        'scheduled_messages',
        'next_send_time',
    )
    op.add_column(
        'scheduled_messages',
        sa.Column(
            'next_send_time',
            sa.VARCHAR(),
            nullable=True,
        ),
    )

    # ### end Alembic commands ###
