"""uniquegroupid

Revision ID: 4961effd8330
Revises: 537eb97ea211
Create Date: 2023-02-26 15:24:48.241303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4961effd8330'
down_revision = '537eb97ea211'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'group_settings', ['group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_settings', type_='unique')
    # ### end Alembic commands ###
