"""create fk on groups

Revision ID: 537eb97ea211
Revises: 30429ea12e82
Create Date: 2023-02-26 15:10:58.023619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537eb97ea211'
down_revision = '30429ea12e82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_settings_group_id_key', 'group_settings', type_='unique')
    op.create_foreign_key(None, 'group_settings', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_settings', type_='foreignkey')
    op.create_unique_constraint('group_settings_group_id_key', 'group_settings', ['group_id'])
    # ### end Alembic commands ###
