"""delete seed

Revision ID: 772ff6f1f180
Revises: f9f393a0868f
Create Date: 2023-02-26 00:13:51.903796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '772ff6f1f180'
down_revision = 'f9f393a0868f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text('DELETE FROM groups'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meta = sa.MetaData()
    meta.reflect(bind=op.get_bind(), only=['groups'])
    groups_table = sa.Table('groups', meta)
    op.bulk_insert(
        groups_table,
        [
            {'name': 'Group 1', 'group_id': -1003123213221},
            {'name': 'Group 2', 'group_id': -1003123213222},
            {'name': 'Group 3', 'group_id': -1003123213223},
            {'name': 'Group 4', 'group_id': -1003123213224},
        ]
    )
    # ### end Alembic commands ###
