""" change group id to bigint

Revision ID: 964c5db6eb96
Revises: cd23c5a8c0df
Create Date: 2023-02-07 03:39:39.817567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964c5db6eb96'
down_revision = 'cd23c5a8c0df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'groups',
        'group_id',
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'groups',
        'group_id',
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
    )

    # ### end Alembic commands ###
