"""message_id_to_nullable

Revision ID: 98fa205df747
Revises: a66306c5db0b
Create Date: 2023-02-24 06:50:55.891927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fa205df747'
down_revision = 'a66306c5db0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_messages', 'message_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_messages', 'message_id', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
