"""add_group_id_to_group_settings

Revision ID: 9c6a51a8364a
Revises: 00c5ee2d42b5
Create Date: 2023-02-23 05:27:05.062555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6a51a8364a'
down_revision = '00c5ee2d42b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_settings', sa.Column('group_id', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_settings', 'group_id')
    # ### end Alembic commands ###
