"""add_template_id_to_scheduled_messages

Revision ID: a66306c5db0b
Revises: 1577dcfbcb07
Create Date: 2023-02-24 06:44:41.822877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66306c5db0b'
down_revision = '1577dcfbcb07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_messages', sa.Column('template_id', sa.INT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_messages', 'template_id')
    # ### end Alembic commands ###
