"""add_photo_column_to_templates

Revision ID: b5056cc0a18a
Revises: c895b6cf2d2d
Create Date: 2023-02-22 05:06:08.664661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5056cc0a18a'
down_revision = 'c895b6cf2d2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'photo')
    # ### end Alembic commands ###
