"""optional for text metemplate

Revision ID: bf62e1c62b8b
Revises: 34ffaf995872
Create Date: 2023-02-25 17:00:56.463660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf62e1c62b8b'
down_revision = '34ffaf995872'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('templates', 'text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
