"""scheduled_group_id_to_bigint

Revision ID: c895b6cf2d2d
Revises: c717ca3b1850
Create Date: 2023-02-16 23:07:58.497403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c895b6cf2d2d'
down_revision = 'c717ca3b1850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_messages', 'group_id', existing_type=sa.INTEGER(), type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_messages', 'group_id', existing_type=sa.BigInteger(), type_=sa.INTEGER())
    # ### end Alembic commands ###
