"""add message link

Revision ID: f9f393a0868f
Revises: 799b2ae743d8
Create Date: 2023-02-25 23:59:54.280004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f393a0868f'
down_revision = '799b2ae743d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_messages', sa.Column('message_link', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_messages', 'message_link')
    # ### end Alembic commands ###
